void initWebServer();
void webServerHandleClient();

extern volatile bool needReboot;
void handleRoot();
void handleNotFound();
void handleTools();
void handleLogs();
void handleReboot();
void handleToolUpdate();
void handleFSbrowser();
void handleReadfile();
void handleSavefile();
void handleLogBuffer();
void handleScanNetwork();
void handleClearConsole();
void handleGetVersion();
void handleGeneral();
void handleSaveGeneral();
void handleConfigWifi();
void handleSaveWifi();
void handleHelp();
